displayName=Skedpojkar
author=mnihl
description=Side panel idle-minigames (birth of Runeclicker, among other minigames), toggleable fun sounds and chat messages triggered from in-game events.
tags=sound,announce,minigame,party,clan,fun
plugins=com.skedpojkar.SkedpojkarPlugin
build=standard
